"""Country registry: the World Bank's 217 non-aggregate economies.

`_ECONOMIES` is generated from `wbgapi`'s `wb.economy.list()` (codes are ISO 3166-1
alpha-3, which the World Bank reuses as its economy code) — regenerate it rather
than hand-editing. It includes territories with their own economic statistics,
such as Hong Kong and Puerto Rico, so the count exceeds the 193 UN members.

`FX` and `FRED_BOND_SERIES` stay hand-maintained: the World Bank publishes neither
a currency mapping nor bond yields. An economy missing from either simply reports
null for that metric rather than a fabricated one.
"""

_ECONOMIES = [
    ("ABW", "Aruba", "Latin America & Caribbean"),
    ("AFG", "Afghanistan", "Middle East & North Africa"),
    ("AGO", "Angola", "Sub-Saharan Africa"),
    ("ALB", "Albania", "Europe & Central Asia"),
    ("AND", "Andorra", "Europe & Central Asia"),
    ("ARE", "United Arab Emirates", "Middle East & North Africa"),
    ("ARG", "Argentina", "Latin America & Caribbean"),
    ("ARM", "Armenia", "Europe & Central Asia"),
    ("ASM", "American Samoa", "East Asia & Pacific"),
    ("ATG", "Antigua and Barbuda", "Latin America & Caribbean"),
    ("AUS", "Australia", "East Asia & Pacific"),
    ("AUT", "Austria", "Europe & Central Asia"),
    ("AZE", "Azerbaijan", "Europe & Central Asia"),
    ("BDI", "Burundi", "Sub-Saharan Africa"),
    ("BEL", "Belgium", "Europe & Central Asia"),
    ("BEN", "Benin", "Sub-Saharan Africa"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa"),
    ("BGD", "Bangladesh", "South Asia"),
    ("BGR", "Bulgaria", "Europe & Central Asia"),
    ("BHR", "Bahrain", "Middle East & North Africa"),
    ("BHS", "Bahamas, The", "Latin America & Caribbean"),
    ("BIH", "Bosnia and Herzegovina", "Europe & Central Asia"),
    ("BLR", "Belarus", "Europe & Central Asia"),
    ("BLZ", "Belize", "Latin America & Caribbean"),
    ("BMU", "Bermuda", "North America"),
    ("BOL", "Bolivia", "Latin America & Caribbean"),
    ("BRA", "Brazil", "Latin America & Caribbean"),
    ("BRB", "Barbados", "Latin America & Caribbean"),
    ("BRN", "Brunei Darussalam", "East Asia & Pacific"),
    ("BTN", "Bhutan", "South Asia"),
    ("BWA", "Botswana", "Sub-Saharan Africa"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa"),
    ("CAN", "Canada", "North America"),
    ("CHE", "Switzerland", "Europe & Central Asia"),
    ("CHI", "Channel Islands", "Europe & Central Asia"),
    ("CHL", "Chile", "Latin America & Caribbean"),
    ("CHN", "China", "East Asia & Pacific"),
    ("CIV", "Cote d'Ivoire", "Sub-Saharan Africa"),
    ("CMR", "Cameroon", "Sub-Saharan Africa"),
    ("COD", "Congo, Dem. Rep.", "Sub-Saharan Africa"),
    ("COG", "Congo, Rep.", "Sub-Saharan Africa"),
    ("COL", "Colombia", "Latin America & Caribbean"),
    ("COM", "Comoros", "Sub-Saharan Africa"),
    ("CPV", "Cabo Verde", "Sub-Saharan Africa"),
    ("CRI", "Costa Rica", "Latin America & Caribbean"),
    ("CUB", "Cuba", "Latin America & Caribbean"),
    ("CUW", "Curacao", "Latin America & Caribbean"),
    ("CYM", "Cayman Islands", "Latin America & Caribbean"),
    ("CYP", "Cyprus", "Europe & Central Asia"),
    ("CZE", "Czechia", "Europe & Central Asia"),
    ("DEU", "Germany", "Europe & Central Asia"),
    ("DJI", "Djibouti", "Middle East & North Africa"),
    ("DMA", "Dominica", "Latin America & Caribbean"),
    ("DNK", "Denmark", "Europe & Central Asia"),
    ("DOM", "Dominican Republic", "Latin America & Caribbean"),
    ("DZA", "Algeria", "Middle East & North Africa"),
    ("ECU", "Ecuador", "Latin America & Caribbean"),
    ("EGY", "Egypt, Arab Rep.", "Middle East & North Africa"),
    ("ERI", "Eritrea", "Sub-Saharan Africa"),
    ("ESP", "Spain", "Europe & Central Asia"),
    ("EST", "Estonia", "Europe & Central Asia"),
    ("ETH", "Ethiopia", "Sub-Saharan Africa"),
    ("FIN", "Finland", "Europe & Central Asia"),
    ("FJI", "Fiji", "East Asia & Pacific"),
    ("FRA", "France", "Europe & Central Asia"),
    ("FRO", "Faroe Islands", "Europe & Central Asia"),
    ("FSM", "Micronesia, Fed. Sts.", "East Asia & Pacific"),
    ("GAB", "Gabon", "Sub-Saharan Africa"),
    ("GBR", "United Kingdom", "Europe & Central Asia"),
    ("GEO", "Georgia", "Europe & Central Asia"),
    ("GHA", "Ghana", "Sub-Saharan Africa"),
    ("GIB", "Gibraltar", "Europe & Central Asia"),
    ("GIN", "Guinea", "Sub-Saharan Africa"),
    ("GMB", "Gambia, The", "Sub-Saharan Africa"),
    ("GNB", "Guinea-Bissau", "Sub-Saharan Africa"),
    ("GNQ", "Equatorial Guinea", "Sub-Saharan Africa"),
    ("GRC", "Greece", "Europe & Central Asia"),
    ("GRD", "Grenada", "Latin America & Caribbean"),
    ("GRL", "Greenland", "Europe & Central Asia"),
    ("GTM", "Guatemala", "Latin America & Caribbean"),
    ("GUM", "Guam", "East Asia & Pacific"),
    ("GUY", "Guyana", "Latin America & Caribbean"),
    ("HKG", "Hong Kong SAR, China", "East Asia & Pacific"),
    ("HND", "Honduras", "Latin America & Caribbean"),
    ("HRV", "Croatia", "Europe & Central Asia"),
    ("HTI", "Haiti", "Latin America & Caribbean"),
    ("HUN", "Hungary", "Europe & Central Asia"),
    ("IDN", "Indonesia", "East Asia & Pacific"),
    ("IMN", "Isle of Man", "Europe & Central Asia"),
    ("IND", "India", "South Asia"),
    ("IRL", "Ireland", "Europe & Central Asia"),
    ("IRN", "Iran, Islamic Rep.", "Middle East & North Africa"),
    ("IRQ", "Iraq", "Middle East & North Africa"),
    ("ISL", "Iceland", "Europe & Central Asia"),
    ("ISR", "Israel", "Middle East & North Africa"),
    ("ITA", "Italy", "Europe & Central Asia"),
    ("JAM", "Jamaica", "Latin America & Caribbean"),
    ("JOR", "Jordan", "Middle East & North Africa"),
    ("JPN", "Japan", "East Asia & Pacific"),
    ("KAZ", "Kazakhstan", "Europe & Central Asia"),
    ("KEN", "Kenya", "Sub-Saharan Africa"),
    ("KGZ", "Kyrgyz Republic", "Europe & Central Asia"),
    ("KHM", "Cambodia", "East Asia & Pacific"),
    ("KIR", "Kiribati", "East Asia & Pacific"),
    ("KNA", "St. Kitts and Nevis", "Latin America & Caribbean"),
    ("KOR", "Korea, Rep.", "East Asia & Pacific"),
    ("KWT", "Kuwait", "Middle East & North Africa"),
    ("LAO", "Lao PDR", "East Asia & Pacific"),
    ("LBN", "Lebanon", "Middle East & North Africa"),
    ("LBR", "Liberia", "Sub-Saharan Africa"),
    ("LBY", "Libya", "Middle East & North Africa"),
    ("LCA", "St. Lucia", "Latin America & Caribbean"),
    ("LIE", "Liechtenstein", "Europe & Central Asia"),
    ("LKA", "Sri Lanka", "South Asia"),
    ("LSO", "Lesotho", "Sub-Saharan Africa"),
    ("LTU", "Lithuania", "Europe & Central Asia"),
    ("LUX", "Luxembourg", "Europe & Central Asia"),
    ("LVA", "Latvia", "Europe & Central Asia"),
    ("MAC", "Macao SAR, China", "East Asia & Pacific"),
    ("MAF", "St. Martin (French part)", "Latin America & Caribbean"),
    ("MAR", "Morocco", "Middle East & North Africa"),
    ("MCO", "Monaco", "Europe & Central Asia"),
    ("MDA", "Moldova", "Europe & Central Asia"),
    ("MDG", "Madagascar", "Sub-Saharan Africa"),
    ("MDV", "Maldives", "South Asia"),
    ("MEX", "Mexico", "Latin America & Caribbean"),
    ("MHL", "Marshall Islands", "East Asia & Pacific"),
    ("MKD", "North Macedonia", "Europe & Central Asia"),
    ("MLI", "Mali", "Sub-Saharan Africa"),
    ("MLT", "Malta", "Middle East & North Africa"),
    ("MMR", "Myanmar", "East Asia & Pacific"),
    ("MNE", "Montenegro", "Europe & Central Asia"),
    ("MNG", "Mongolia", "East Asia & Pacific"),
    ("MNP", "Northern Mariana Islands", "East Asia & Pacific"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa"),
    ("MRT", "Mauritania", "Sub-Saharan Africa"),
    ("MUS", "Mauritius", "Sub-Saharan Africa"),
    ("MWI", "Malawi", "Sub-Saharan Africa"),
    ("MYS", "Malaysia", "East Asia & Pacific"),
    ("NAM", "Namibia", "Sub-Saharan Africa"),
    ("NCL", "New Caledonia", "East Asia & Pacific"),
    ("NER", "Niger", "Sub-Saharan Africa"),
    ("NGA", "Nigeria", "Sub-Saharan Africa"),
    ("NIC", "Nicaragua", "Latin America & Caribbean"),
    ("NLD", "Netherlands", "Europe & Central Asia"),
    ("NOR", "Norway", "Europe & Central Asia"),
    ("NPL", "Nepal", "South Asia"),
    ("NRU", "Naoero", "East Asia & Pacific"),
    ("NZL", "New Zealand", "East Asia & Pacific"),
    ("OMN", "Oman", "Middle East & North Africa"),
    ("PAK", "Pakistan", "Middle East & North Africa"),
    ("PAN", "Panama", "Latin America & Caribbean"),
    ("PER", "Peru", "Latin America & Caribbean"),
    ("PHL", "Philippines", "East Asia & Pacific"),
    ("PLW", "Palau", "East Asia & Pacific"),
    ("PNG", "Papua New Guinea", "East Asia & Pacific"),
    ("POL", "Poland", "Europe & Central Asia"),
    ("PRI", "Puerto Rico (US)", "Latin America & Caribbean"),
    ("PRK", "Korea, Dem. People's Rep.", "East Asia & Pacific"),
    ("PRT", "Portugal", "Europe & Central Asia"),
    ("PRY", "Paraguay", "Latin America & Caribbean"),
    ("PSE", "West Bank and Gaza", "Middle East & North Africa"),
    ("PYF", "French Polynesia", "East Asia & Pacific"),
    ("QAT", "Qatar", "Middle East & North Africa"),
    ("ROU", "Romania", "Europe & Central Asia"),
    ("RUS", "Russian Federation", "Europe & Central Asia"),
    ("RWA", "Rwanda", "Sub-Saharan Africa"),
    ("SAU", "Saudi Arabia", "Middle East & North Africa"),
    ("SDN", "Sudan", "Sub-Saharan Africa"),
    ("SEN", "Senegal", "Sub-Saharan Africa"),
    ("SGP", "Singapore", "East Asia & Pacific"),
    ("SLB", "Solomon Islands", "East Asia & Pacific"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa"),
    ("SLV", "El Salvador", "Latin America & Caribbean"),
    ("SMR", "San Marino", "Europe & Central Asia"),
    ("SOM", "Somalia, Fed. Rep.", "Sub-Saharan Africa"),
    ("SRB", "Serbia", "Europe & Central Asia"),
    ("SSD", "South Sudan", "Sub-Saharan Africa"),
    ("STP", "Sao Tome and Principe", "Sub-Saharan Africa"),
    ("SUR", "Suriname", "Latin America & Caribbean"),
    ("SVK", "Slovak Republic", "Europe & Central Asia"),
    ("SVN", "Slovenia", "Europe & Central Asia"),
    ("SWE", "Sweden", "Europe & Central Asia"),
    ("SWZ", "Eswatini", "Sub-Saharan Africa"),
    ("SXM", "Sint Maarten (Dutch part)", "Latin America & Caribbean"),
    ("SYC", "Seychelles", "Sub-Saharan Africa"),
    ("SYR", "Syrian Arab Republic", "Middle East & North Africa"),
    ("TCA", "Turks and Caicos Islands", "Latin America & Caribbean"),
    ("TCD", "Chad", "Sub-Saharan Africa"),
    ("TGO", "Togo", "Sub-Saharan Africa"),
    ("THA", "Thailand", "East Asia & Pacific"),
    ("TJK", "Tajikistan", "Europe & Central Asia"),
    ("TKM", "Turkmenistan", "Europe & Central Asia"),
    ("TLS", "Timor-Leste", "East Asia & Pacific"),
    ("TON", "Tonga", "East Asia & Pacific"),
    ("TTO", "Trinidad and Tobago", "Latin America & Caribbean"),
    ("TUN", "Tunisia", "Middle East & North Africa"),
    ("TUR", "Turkiye", "Europe & Central Asia"),
    ("TUV", "Tuvalu", "East Asia & Pacific"),
    ("TZA", "Tanzania", "Sub-Saharan Africa"),
    ("UGA", "Uganda", "Sub-Saharan Africa"),
    ("UKR", "Ukraine", "Europe & Central Asia"),
    ("URY", "Uruguay", "Latin America & Caribbean"),
    ("USA", "United States", "North America"),
    ("UZB", "Uzbekistan", "Europe & Central Asia"),
    ("VCT", "St. Vincent and the Grenadines", "Latin America & Caribbean"),
    ("VEN", "Venezuela, RB", "Latin America & Caribbean"),
    ("VGB", "British Virgin Islands", "Latin America & Caribbean"),
    ("VIR", "Virgin Islands (U.S.)", "Latin America & Caribbean"),
    ("VNM", "Viet Nam", "East Asia & Pacific"),
    ("VUT", "Vanuatu", "East Asia & Pacific"),
    ("WSM", "Samoa", "East Asia & Pacific"),
    ("XKX", "Kosovo", "Europe & Central Asia"),
    ("YEM", "Yemen, Rep.", "Middle East & North Africa"),
    ("ZAF", "South Africa", "Sub-Saharan Africa"),
    ("ZMB", "Zambia", "Sub-Saharan Africa"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa"),
]

# Yahoo Finance tickers quoting "USD per 1 unit of local currency". The euro entries
# share one ticker, so the fetch deduplicates them into a single request. The US is
# absent by design: USD is the quote currency.
FX = {
    "ARG": ("ARSUSD=X", "ARS / USD"),
    "AUS": ("AUDUSD=X", "AUD / USD"),
    "AUT": ("EURUSD=X", "EUR / USD"),
    "BEL": ("EURUSD=X", "EUR / USD"),
    "BRA": ("BRLUSD=X", "BRL / USD"),
    "CAN": ("CADUSD=X", "CAD / USD"),
    "CHE": ("CHFUSD=X", "CHF / USD"),
    "CHN": ("CNYUSD=X", "CNY / USD"),
    "CYP": ("EURUSD=X", "EUR / USD"),
    "DEU": ("EURUSD=X", "EUR / USD"),
    "EGY": ("EGPUSD=X", "EGP / USD"),
    "ESP": ("EURUSD=X", "EUR / USD"),
    "EST": ("EURUSD=X", "EUR / USD"),
    "FIN": ("EURUSD=X", "EUR / USD"),
    "FRA": ("EURUSD=X", "EUR / USD"),
    "GBR": ("GBPUSD=X", "GBP / USD"),
    "GRC": ("EURUSD=X", "EUR / USD"),
    "HRV": ("EURUSD=X", "EUR / USD"),
    "IDN": ("IDRUSD=X", "IDR / USD"),
    "IND": ("INRUSD=X", "INR / USD"),
    "IRL": ("EURUSD=X", "EUR / USD"),
    "ITA": ("EURUSD=X", "EUR / USD"),
    "JPN": ("JPYUSD=X", "JPY / USD"),
    "KOR": ("KRWUSD=X", "KRW / USD"),
    "LTU": ("EURUSD=X", "EUR / USD"),
    "LUX": ("EURUSD=X", "EUR / USD"),
    "LVA": ("EURUSD=X", "EUR / USD"),
    "MEX": ("MXNUSD=X", "MXN / USD"),
    "MLT": ("EURUSD=X", "EUR / USD"),
    "NGA": ("NGNUSD=X", "NGN / USD"),
    "NLD": ("EURUSD=X", "EUR / USD"),
    "NOR": ("NOKUSD=X", "NOK / USD"),
    "NZL": ("NZDUSD=X", "NZD / USD"),
    "POL": ("PLNUSD=X", "PLN / USD"),
    "PRT": ("EURUSD=X", "EUR / USD"),
    "RUS": ("RUBUSD=X", "RUB / USD"),
    "SAU": ("SARUSD=X", "SAR / USD"),
    "SGP": ("SGDUSD=X", "SGD / USD"),
    "SVK": ("EURUSD=X", "EUR / USD"),
    "SVN": ("EURUSD=X", "EUR / USD"),
    "SWE": ("SEKUSD=X", "SEK / USD"),
    "THA": ("THBUSD=X", "THB / USD"),
    "TUR": ("TRYUSD=X", "TRY / USD"),
    "VNM": ("VNDUSD=X", "VND / USD"),
    "ZAF": ("ZARUSD=X", "ZAR / USD"),
}

COUNTRIES = [
    {
        "code": code,
        "name": name,
        "region": region,
        "wb_code": code,
        "fx_ticker": FX.get(code, (None, None))[0],
        "fx_pair": FX.get(code, (None, None))[1],
    }
    for code, name, region in _ECONOMIES
]

# FRED's mirror of OECD's long-term (10y) government bond yield series. FRED carries
# these under two different id shapes, and a country may exist under one but not the
# other — probe both before concluding a country has no series:
#   `IRLTLT01<ISO2>M156N`  the long-standing OECD form
#   `<ISO3>IRLTLT01STM`    a later form, carrying India, Colombia and the Baltics
#
# Every entry below was probed against FRED and returns a current value; economies
# absent here report a null bond_yield_10y with an empty history. Coverage tops out
# near the OECD membership because most economies have no liquid 10-year
# local-currency sovereign bond to quote — the limit is the instrument, not the API.
#
# Probed under both forms and genuinely unavailable, so nobody re-guesses them:
# BRA, CHN, IDN, EST and ISL have no usable series; RUS and TUR have real ones that
# stopped updating and are rejected by the staleness guard in services/fred.py.
FRED_BOND_SERIES = {
    "AUS": "IRLTLT01AUM156N",
    "AUT": "IRLTLT01ATM156N",
    "BEL": "IRLTLT01BEM156N",
    "CAN": "IRLTLT01CAM156N",
    "CHE": "IRLTLT01CHM156N",
    "CHL": "IRLTLT01CLM156N",
    "COL": "COLIRLTLT01STM",
    "CRI": "CRIIRLTLT01STM",
    "CZE": "IRLTLT01CZM156N",
    "DEU": "IRLTLT01DEM156N",
    "DNK": "IRLTLT01DKM156N",
    "ESP": "IRLTLT01ESM156N",
    "FIN": "IRLTLT01FIM156N",
    "FRA": "IRLTLT01FRM156N",
    "GBR": "IRLTLT01GBM156N",
    "GRC": "IRLTLT01GRM156N",
    "HUN": "IRLTLT01HUM156N",
    "IND": "INDIRLTLT01STM",
    "IRL": "IRLTLT01IEM156N",
    "ISR": "IRLTLT01ILM156N",
    "ITA": "IRLTLT01ITM156N",
    "JPN": "IRLTLT01JPM156N",
    "KOR": "IRLTLT01KRM156N",
    "LTU": "LTUIRLTLT01STM",
    "LUX": "IRLTLT01LUM156N",
    "LVA": "LVAIRLTLT01STM",
    "MEX": "IRLTLT01MXM156N",
    "NLD": "IRLTLT01NLM156N",
    "NOR": "IRLTLT01NOM156N",
    "NZL": "IRLTLT01NZM156N",
    "POL": "IRLTLT01PLM156N",
    "PRT": "IRLTLT01PTM156N",
    "SVK": "IRLTLT01SKM156N",
    "SVN": "IRLTLT01SIM156N",
    "SWE": "IRLTLT01SEM156N",
    "USA": "IRLTLT01USM156N",
    "ZAF": "IRLTLT01ZAM156N",
}


def get_country_config(code: str) -> dict | None:
    code = code.upper()
    return next((c for c in COUNTRIES if c["code"] == code), None)


def list_country_configs() -> list[dict]:
    return COUNTRIES
